# Configuración base
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# PRODUCCIÓN (RENDER + RAILS 8)
# Fíjate que ahora definimos 3 bloques: primary, cache y queue
# PRODUCCIÓN (RENDER + RAILS 8)
production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>
  
  cache:
    <<: *primary_production
    
  queue:
    <<: *primary_production
    
  cable:
    <<: *primary_production